config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :works
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  root to: 'pages#home'

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :subject
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject =>  "#{subject}",
      :to => "kongu3333@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/work.rb
class Work < ActiveRecord::Base
	
	mount_uploader :main_image, MainImageUploader
	mount_uploader :head_image, HeadImageUploader

	def prev
	  self.class.where(['"index" < ?',index]).last
	end

	def next
	  self.class.where(['"index" > ?',index]).first
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      #flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
      respond_to do |format|
          format.js {@name = @contact.name}
      end
    else
      respond_to do |format|
          format.js {render :template => 'failsend'}
      end
    end
  end

  

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@works = Work.all.limit(4)
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:show, :index]
  skip_before_action :verify_authenticity_token

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { render :edit, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:name, :index, :body, :main_image, :head_image, :gdesign, :wdesign, :wdevel, :published)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def bodyclass(controller)
		if current_page?('/')
			front = "front"
		else
			front = "not-front"
		end

		if user_signed_in?
			session ="logged-in"
		else
			session ="not-logged-in"
		end

		return (controller.controller_name+" "+controller.action_name+" "+front+" "+session)		
	end

	def editable
		if user_signed_in?
			return ("editable")
		end
	end

	def front
		 return current_page?('/')
	end

	def new_contact
	  Contact.new    
	end
		
			


end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/create.js.erb
$('#contactform').html("Thanks <span class='accent-yellow'> <%=j @name %></span>. </br>We will get back to you soon!").fadeTo(100, .1).delay(100).fadeTo(500, 1);;

app/views/contacts/failsend.js.erb
$('#contactform').html("Thanks xx </br>We will get back to you soon!").fadeTo(100, .1).delay(100).fadeTo(500, 1);;

app/views/contacts/new.html.erb
<%= simple_form_for @contact do |f| %>
  <div class="row half no-collapse-1">
    <div class="6u">
      <%= f.input :name, :required => true %>
    </div>
    <div class="6u">
      <%= f.input :email, :required => true %>
    </div>
  </div>
  <div class="row half">
    <div class="12u">
     <%= f.input :subject, :required => true %>
    </div>
  </div>
  <div class="row half">
    <div class="12u">
      <%= f.input :message, :as => :text, :required => true %>
    </div>
  </div>
  <div class= "hidden">
    <%= f.input :nickname, :hint => 'Leave this field blank!' %>
  </div>
  <div class="row half">
    <div class="12u">
      <ul class="buttons">
         <%= f.button :submit, 'Send message', :class=> "button special" %>
      </ul>
    </div>
  </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="js/jquery.dropotron.min.js"></script>
  <script src="/js/skel.min.js"></script>
  <script src="js/skel-layers.min.js"></script>
  <script src="js/init.js"></script>
  <noscript>
    <link rel="stylesheet" href="css/skel.css" />
    <link rel="stylesheet" href="css/style.css" />
    <link rel="stylesheet" href="css/style-noscript.css" />
  </noscript>
  <!--[if lte IE 8]><link rel="stylesheet" href="css/ie/v8.css" /><![endif]-->
  <!--[if lte IE 9]><link rel="stylesheet" href="css/ie/v9.css" /><![endif]-->
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,700|Arvo' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body class='<%= bodyclass(controller)%>' >
  <% flash.each do |key, value| %>
  <div class="container noticewrap">  
    <p id="notice"><%= notice %></p>
  </div>
<% end %>
  
  
<%= render "partials/header"%>

<div id="main">
	<%= yield %>
</div>

<%= render "partials/footer"%>

</body>
</html>

app/views/pages/home.html.erb
				<!-- Two -->
			</br>
					<section class="wrapper style1 container special">
						<div class="row" id ="triptich">
							<div class="4u">
							
								<section>
									<img src="css/images/graphic-design.png">
									<header>
										 <h3>Graphic Design</h3>
									</header>
									<p>Sed tristique purus vitae volutpat ultrices. Aliquam eu elit eget arcu commodo suscipit dolor nec nibh. Proin a ullamcorper elit, et sagittis turpis. Integer ut fermentum.</p>
								</section>
							
							</div>
							<div class="4u">
							
								<section>
									<img src="css/images/web-design.png">
									<header>
										<h3>Web Design</h3>
									</header>
									<p>Sed tristique purus vitae volutpat ultrices. Aliquam eu elit eget arcu commodo suscipit dolor nec nibh. Proin a ullamcorper elit, et sagittis turpis. Integer ut fermentum.</p>
								</section>
							
							</div>
							<div class="4u">
							
								<section>
									<img src="css/images/web-development.png">
									<header>
										<h3>Web Development</h3>
									</header>
									<p>Sed tristique purus vitae volutpat ultrices. Aliquam eu elit eget arcu commodo suscipit dolor nec nibh. Proin a ullamcorper elit, et sagittis turpis. Integer ut fermentum.</p>
									<span id="work"></span>
								</section>
							
							</div>
						</div>
					</section>
<!-- PORTFOLIO -->
					<section class=" container">
					
						<header class="proj">
							<h2>PROJECTS</h2>
						</header>

						
						<div class="row">
							<% @works.each_slice(2) do |i| %>

								<div class="row">
									<% i.each do |work| %>

									<div class="6u port-item ">
							
										<section class="<%=editable%>">
											<%= link_to(work, :class=>"image feature") do %>
												<%= image_tag work.main_image_url %>
											<%end%>
											<a href="#" class="image feature"> </a>
											<header>
												<%= link_to work do %>
													<h3><span class=""><%=work.name%></span></h3>
												<i class="fa fa-external-link-square"></i>
												<%end%>												
											</header>
											 <% if user_signed_in? %>
					                          <%= link_to 'Show', work %>
					                          <%= link_to 'Edit', edit_work_path(work) %>
					                          <%= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you sure?' } %>
					                        <%end%>
											
										</section>

									</div>

										
									<%end%>
								</div>

							<%end%>
						</div>

					      
					   
						
						

						</div>
						<p></p>

						<footer class="major">
							<ul class="buttons">
								<li><a href="/works" class="button">ALL PROJECTS</a></li>
							</ul>
						</footer>
					<p></p>
					</section>

				

app/views/partials/_contactform.html.erb
<%= simple_form_for Contact.new, remote:true do |f| %>
  <div class="row half no-collapse-1">
    <div class="6u">
      <%= f.input :name, :required => true %>
    </div>
    <div class="6u">
      <%= f.input :email, :required => true %>
    </div>
  </div>
  <div class="row half">
    <div class="12u">
     <%= f.input :subject, :required => true %>
    </div>
  </div>
  <div class="row half">
    <div class="12u">
      <%= f.input :message, :as => :text, :required => true %>
    </div>
  </div>
  <div class= "hidden">
    <%= f.input :nickname, :hint => 'Leave this field blank!' %>
  </div>
  <div class="row half">
    <div class="12u">
    </br>
      <%= f.button :submit, 'Send message', :class=> "button special" %>
    </div>
  </div>
<%end%>

app/views/partials/_footer.html.erb
<footer id="footer">
				<section class="container ">
					<div class="row">
					<div class="6u">
					<img src="<%= asset_path('gfp-studio-logo.svg') %>">
						<ul class="icons">
						<li><a href="#"><span class="icon feature fa-facebook-square fa-2"></span></a></li>
						<li><a href="#"><span class="icon feature fa-twitter-square fa-2"></span></a></li>
						<li><a href="#"><span class="icon feature fa-flickr fa-2"></span></a></li>
						<li><a href="#"><span class="icon feature fa-google-plus fa-2"></span></a></li>
						
					</ul>
					<address>
						<p><span class="accent-yellow">e:</span> hello@gfpstudio.com <br>
						<span class="accent-yellow">t:</span> +353 85 1920 495 </p>
						<p>4 Rivervale, Rathborne<br>
						Ashtown, D15 <br>
						Dublin, Ireland</p>
					</address>

					
					</div>
					<div class="6u">
					<div id="contactform">
					<p>Get in <span class="accent-yellow">touch</span><span id="contact"></span></p>
							<%= render "partials/contactform"%>
						</div>		
					</div>
					</div>
					<div class="row">
						<p></p>
						<span class="copyright 12u"><span class="accent-azul">&copy; GFP Studio. All rights reserved. 2011-<%= Time.now.year %></span></span>
						<% if user_signed_in? %>
  <p>Welcome <%= current_user.email %></p>
  <%= link_to 'Logged In [click to logout]', destroy_user_session_path, :method => :delete %>
<% else %>
  <p>You are not signed in.</p>
  <%= link_to 'Login', new_user_session_path %>
<% end %>
					</div>
					</section>

			</footer>

app/views/partials/_header.html.erb
<header id="header" class="alt">
	<div class="container">
		<h1 id="logo"><a href="/"><img src="<%= asset_path('gfp-studio-logo.svg') %>"></span></a></h1>
		<%= render "partials/mainnav" %>
	</div>
</header>

<div id="moblogo">
	<a href="/"><img src="<%= asset_path('gfp-studio-logo.svg') %>"></span></a>
</div>

<% if current_page?('/')%>
	<%= render "partials/headers/homehead" %>
<%elsif current_page?('/works')%>
	<%= render "partials/headers/workhead" %>
<%elsif  ((params[:action] == "show") && ((params[:controller] == "works")))%>
	<%= render "partials/headers/workitemhead" %>
<%else%>
	<%= render "partials/headers/elsehead" %>
<% end %>

			

app/views/partials/_mainnav.html.erb
<nav id="nav">
	<%if ((params[:controller])=='works')%>
		<ul>
			<li ><a href="/#main">Services</a></li>
			<li class="current"><%= link_to "Work", works_path %></li>
			<li ><a href="#contact" class="scrolly">Contact</a></li>
		</ul>
	<%else%>

		<ul>
			<li ><a href="#main" class="scrolly">Services</a></li>
			<li ><a href="#work" class="scrolly">Work</a></li>
			<li ><a href="#contact" class="scrolly">Contact</a></li>
		</ul>

	<%end%>
</nav>

app/views/partials/_portbottomnav.html.erb
<div class="container">
<div class="row ">
		
<div class="-2u 8u ">

<hr>
	<div class="row">
		<%if @work.prev!=nil %>
		<div class="6u port-item">Prev<br>
			<section>
				
				<a href="<%=@work.prev.id%>" class="image feature"><img src="<%=@work.prev.main_image%>" alt="" /></a>
				<header>
					<a href="<%=@work.prev.id%>"><h3><span class=""><%=@work.prev.name%></span></h3>
						<i class="fa fa-external-link-square"></i>
					</a>
				</header>
				
			</section>
		</div>
		<%end%>

		<%if @work.next!=nil %>
		<div class="6u port-item">Next <br>
			<section>
				<a href="<%=@work.next.id%>" class="image feature"><img src="<%=@work.next.main_image%>" alt="" /></a>
				<header>
					<a href="<%=@work.next.id%>"><h3><span class=""><%=@work.next.name%></span></h3>
						<i class="fa fa-external-link-square"></i>
					</a>
				</header>
				
			</section>
		</div>
		<%end%>
	</div>
		
</div>


</div>

</section>
</div >
<p></p>

<div class="container">
	<footer class="major">
		<ul class="buttons">
			<li><a href="/works" class="button">ALL PROJECTS</a></li>
		</ul>
	</footer>
</div>

app/views/partials/headers/_elsehead.html.erb
<section id="banner">			
	<div class="container">
		<div class="inner">
			
			<header>
				<h2 id="jumbotext"><%=controller.controller_name+" "+controller.action_name%></h2>
			</header>
			<p>A few <span class="accent-yellow">examples</span> of what kept us busy</p>
				
		</div>
	</div>
</section>

app/views/partials/headers/_homehead.html.erb
<section id="banner">
				
	<ul id="slider">
		<li id= "first-s" class="parallax"></li>
		<li id= "second-s" class="parallax"></li>
		<li id= "third-s" class="parallax"></li>
	</ul>
				
	<div id="effects"></div>

	<div class="inner">
		
		<header>
			<h2 id="jumbotext"><span class="nowrap"><span class="accent-azul inter">GRAPHIC</span> DESIGN.</span><span class="breaker"> </span><span class="nowrap"><span class="accent-yellow inter">WEB </span>DESIGN.<span class="breaker"> </span></span><span class="nowrap">WEB <span class="accent-red inter">DEVELOPEMENT.</span></span></h2>
		</header>
		
		<p>High Impact Designs and Bespoke Code</p>

		<footer>
			<ul class="buttons vertical">
				<li><a href="#main" class="button scrolly">SEE MORE</a></li>
			</ul>
		</footer>
	
	</div>
				
</section>

app/views/partials/headers/_workhead.html.erb
<section id="banner">			
	<div class="container">
		<div class="inner">
			
			<header>
				<h2 id="jumbotext"></span></span><span class="nowrap">OUR <span class="accent-azul inter">WORK </span>SO FAR</span></h2>
			</header>
			<p>A few <span class="accent-yellow">examples</span> of what kept us busy</p>
				
		</div>
	</div>
</section>

app/views/partials/headers/_workitemhead.html.erb
<section id="banner" <%if !(params[:action] == "new")%><%end%>>

<div class="container">
	<div class="inner">

		<h1 class="proj-title"> <%=@work.name%></h1>

		

	</div>
</div>

</section>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/works/_form.html.erb
<%= form_for @work,remote:true, :html => { :multipart => true } do |f| %>
  <% if @work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% @work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p><div class="field">
      <%= f.label :body %><br>
      <%= f.text_area :body, :rows => "10"%>
    </div></p>
  <p><div class="actions">
      <%= f.submit %>
    </div></p>

  <p><div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div></p>
  <p><div class="field">
      <%= f.label :gdesign, 'Graphic Design?' %><br>
      <%= f.check_box :gdesign%>
    </div></p>
    <p><div class="field">
      <%= f.label :wdesign, 'Web Design?' %><br>
      <%= f.check_box :wdesign%>
    </div></p>
    <p><div class="field">
      <%= f.label :wdevel, 'Web Development?' %><br>
      <%= f.check_box :wdevel%>
    </div></p>
    <p><div class="field">
      <%= f.label :published, 'Published?' %><br>
      <%= f.check_box :published%>
    </div></p>
  <p><div class="field">
      <%= f.label :index %><br>
      <%= f.number_field :index %>
    </div></p>
  <p><div class="field upload">
      <label>
        <%= f.file_field :main_image %>
        Upload Main Image
    </label>
    </div></p>
  <p><div class="field upload">
      <label>
      <%= f.file_field :head_image %>
      Upload Head Image
    </label>
    </div></p>
  
<% end %>

app/views/works/edit.html.erb
<div class="container">
	<h1>Editing work</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @work %> |
	<%= link_to 'Back', works_path %>
</div>

app/views/works/index.html.erb
<section class=" container">
          
            

            
            <div class="row">
              <% @works.each_slice(2) do |i| %>

                <div class="row">
                  <% i.each do |work| %>

                  <div class="6u port-item">
              
                    <section class="<%=editable%>">
                      <%= link_to(work, :class=>"image feature") do %>
                        <%= image_tag work.main_image_url %>
                      <%end%>
                      <a href="#" class="image feature"> </a>
                      <header>
                        <%= link_to work do %>
                          <h3><span class=""><%=work.name%></span></h3>
                        <i class="fa fa-external-link-square"></i>
                        <%end%>
                        
                        
                      </header>
                        <% if user_signed_in? %>
                          <%= link_to 'Show', work %>
                          <%= link_to 'Edit', edit_work_path(work) %>
                          <%= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you sure?' } %>
                        <%end%>
                    </section>

                  </div>

                    
                  <%end%>
                </div>

              <%end%>
            </div>

                
             
            
            

            </div>
            
            <% if user_signed_in? %>
            <footer class="major">
              <ul class="buttons">
                <li><%= link_to 'New Work', new_work_path, :class=>"button" %></li>
              </ul>
            </footer>
            <% else %>
          <p></p><br>
          <p></p>
          <%end%>
          </section>
        
     

app/views/works/new.html.erb
<div class="container">
	<h1>New work</h1>

	<%= render 'form' %>

	<%= link_to 'Back', works_path %>
<p></p>
</div>

app/views/works/show.html.erb
<div class="container" >
	<%if @work.gdesign==true || @work.wdesign==true ||@work.wdevel==true %>
	<ul class="badges horisontal cf" >
		<%if @work.gdesign==true %>
			<li><img id="main-image" src="http://localhost:3000/css/images/graphic-design.png"></li>
		<%end%>
		<%if @work.wdesign==true %>
			<li><img id="main-image" src="http://localhost:3000/css/images/web-design.png"></li>
		<%end%>
		<%if @work.wdevel==true %>
			<li><img id="main-image" src="http://localhost:3000/css/images/web-development.png"></li>
		<%end%>
	</ul>
	<%end%>
</div>


<section id="content">
<%=raw @work.body%>
</section>

<% if user_signed_in? %>						
<div class="container adminlinks">
	<div>
	
	<%= link_to 'Edit', edit_work_path(@work) %> |
	<%= link_to 'Back', works_path %> |
	<%= link_to 'Destroy', @work, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"accent-red" %>
	</div>
</div>
<%end%>



<%= render "partials/portbottomnav"%>